#!/usr/bin/env python
#-*- mode: python -*-

from subprocess import Popen, PIPE
import sys

def run(command):
    p = Popen(command.split(), stdout=PIPE, stderr=PIPE)
    p.wait()
    return p.returncode, p.stdout.read().strip().split(), p.stderr.read()


def main():
  _, files_modified, _= run("git diff --name-only --cached")
  print(files_modified)
  for fname in files_modified:
    if fname.lower().endswith(('.pem', '.key', '.ppk')):
       print("Commit failed: Keys in the commit")
       return 1
    with open(fname) as f:
      for line in f:
	if line is "-----BEGIN RSA PRIVATE KEY-----"
            print("Commit failed: Keys in the commit")
            return 1
        mystring = line.split(" ")
        for s in mystring:
          s = s[1:-1]
          matchobj = re.match(r'(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40,80}(?![A-Za-z0-9/+=])',s)
          match = re.match(r'(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])', s)
          if (matchobj is not None) | (match is not None):
             print("Commit failed: Keys in the commit")
             return 1
  return 0

if __name__ == "__main__":
    sys.exit(main())
